# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-26 22:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20180226_2200'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='pub_date',
            field=models.DateField(null=True),
        ),
    ]
