# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-10 18:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='contact_info',
            field=models.ManyToManyField(blank=True, default=None, to='resume.Contact_Info'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='sections',
            field=models.ManyToManyField(blank=True, default=None, to='resume.Section'),
        ),
    ]
